name: Python lint

on:
  pull_request:

jobs:
  flake8_py3:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          flake8 ./